### ISSUE TITLE
Control panel motor doesn't stop

### ISSUE THREAD

**Issue by CodingKoopa** [longwood564/Robot2020#37]
The control panel motor doesn't always stop when exiting control panel mode. This could be fixed by adding an outer `else` setting the motor to `0` in [this](https://github.com/RyanStyron/Robot2020/blob/a9df2e895d5d5db407a69ce34adda722c7540463/src/main/java/frc/robot/Robot.java#L560) method.

**Comment by RyanStyron** [comment]
This issue has been [resolved](https://github.com/longwood564/Robot2020/pull/36/commits/000002dbe89c796348712ee5dbc6977b0dc6912a).
